FROM python:3.11-slim

ARG VERSION
ARG CHECKSUM

WORKDIR /app

ADD --checksum=sha256:${CHECKSUM} https://github.com/MrDave/StaticJinjaPlus/archive/refs/${VERSION}.tar.gz /tmp/app.tar.gz

RUN tar xzf /tmp/app.tar.gz --strip-components=1 -C /app && rm /tmp/app.tar.gz

RUN pip install --no-cache-dir --break-system-packages -r /app/requirements.txt

ENTRYPOINT ["python3", "main.py"]
CMD ["--srcpath", "/app/templates", "--outpath", "/app/output"]
